ProjectHTU/Controllers/EmailController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net;

namespace ProjectHTU.Controllers
{
    public class EmailController : Controller
    {
        
        public async Task<IActionResult> SendEmail(int Id)
        {
            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
            MailMessage mail = new MailMessage();
            SmtpClient smtpServer = new SmtpClient("smtp.gmail.com", 587);
            mail.From = new MailAddress("Apprenticeship@gmail.com");
            smtp.Credentials = new NetworkCredential("Apprenticeship@gmail.com", "xxzk ikqv xrhe boic");

            if (User.IsInRole("TEAMLEADER"))
            {
                mail.To.Add("studentemail@gmail.com");
                mail.Subject = "Assignment";
                mail.Body = $"Dear Student \n \nYou have New Assignment \nCheck on it \n\n{DateTime.Now} ";
            }
            else if (User.IsInRole("STUDENT"))
            {
                mail.To.Add("teamleaderemail@gmail.com");
                mail.Subject = " Report ";
                mail.Body = $"Dear TeamLeader \n \nYou Recived a New Report \nCheck on it \n\n{DateTime.Now} ";
            }
            else
            {
                mail.To.Add("viitoremail@gmail.com");
                mail.Subject = " Visitor ";
                mail.Body = $"Dear Visitor \n \nWe will answer your question as soon as possible \n\n{DateTime.Now} ";
            }
            
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = false;

            try
            {
                await smtp.SendMailAsync(mail);
                if (User.IsInRole("TEAMLEADER"))
                {
                    return RedirectToAction("TeamleaderIndex", "Assignment", new { Id = Id });
                }
                else if (User.IsInRole("STUDENT"))
                {
                    return RedirectToAction("Report", "Student", new { Id = Id });
                }
                else
                {
                    return RedirectToAction("Index", "Home", new { Id = Id });

                }

            }
            catch (Exception ex)
            {
                return BadRequest($"Failed to send email: {ex.Message}");

            }
        }
    }
}

ProjectHTU/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectHTU.Data;
using ProjectHTU.Entities;
using ProjectHTU.Models;
using System.Diagnostics;
using System.Security.Claims;

namespace ProjectHTU.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        ApplicationDbContext context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            this.context =
                context;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)

                if (User.IsInRole("TEAMLEADER")) { return RedirectToAction("IndexUser", new { Id = User.FindFirst(ClaimTypes.NameIdentifier).Value }); }
                else if (User.IsInRole("STUDENT")) { return RedirectToAction("IndexUser", new { Id = User.FindFirst(ClaimTypes.NameIdentifier).Value }); }
                else if (User.IsInRole("ADMIN")) { return RedirectToAction("IndexUser", new { Id = User.FindFirst(ClaimTypes.NameIdentifier).Value }); }
                else if (User.IsInRole("SCHOOLSUPERVISOR")) { return RedirectToAction("IndexUser", new { Id = User.FindFirst(ClaimTypes.NameIdentifier).Value }); }

            return View();
        }

        public IActionResult IndexUser(string Id)
        {
            return View(new { Id = Id });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [HttpPost]
        [Authorize(Roles = "TEAMLEADER , STUDENT")]
        public IActionResult UploadFile(IFormFile formFile)
        {
            Document document = new Document();
            if (formFile.Length > 0)
            {
                Stream st = formFile.OpenReadStream();
                using (BinaryReader br = new BinaryReader(st))
                {
                    var byteFile = br.ReadBytes((int)st.Length);
                    document.file = byteFile;
                }
            }
            document.documentName = formFile.FileName;
            document.contentType = formFile.ContentType;
            context.documents.Add(document);
            context.SaveChanges();

            return RedirectToAction("Index");
        }


        [Authorize]
        public FileStreamResult GetFile(long documentId)
        {
            var file = context.documents.Where(x => x.documentId == documentId).SingleOrDefault();
            Stream stream = new MemoryStream(file.file);
            return new FileStreamResult(stream, file.contentType);
        }

    }
}

ProjectHTU/Views/Home/Index.cshtml
@using ProjectHTU.Entities;
@{
    ViewData["Title"] = "Home Page";
}

<!-- End Navbar -->
<section id="hero">

    <div class="hero-container" data-aos="fade-in">
        <h1>Welcome to Apprenticeship</h1>
        <h2> Effective Communication Between Member On System </h2>
        <img src="assets/img/intro2.png" width="600"
             height="450" alt="Hero Imgs" data-aos="zoom-out" data-aos-delay="100">
    </div>
</section><!-- End Hero Section -->

<section id="testimonials" class="padd-section text-center">
    <div class="container" data-aos="fade-up">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="testimonials-content">
                    <div id="carousel-example-generic" class="carousel slide" data-bs-ride="carousel">

                        <div class="carousel-inner" role="listbox">

                            <div class="carousel-item  active">
                                <div class="top-top">

                                    <h2>ADMIN</h2>
                                    <p>
                                        My experience with the system as an admin was that there was security in dealing with the system. Each user has specific permissions, and the permissions of other people, whether users or visitors, cannot be accessed.

                                        My powers include: Adding a new admin or any user only through me and modifying them or deleting them from the system.
                                        Good experience
                                    </p>
                                    <h4>Rawan Duglass<span> ADMIN </span></h4>

                                </div>
                            </div>

                            <div class="carousel-item ">
                                <div class="top-top">

                                    <h2>STUDENT</h2>
                                    <p>
                                        As a student trainee, I used to follow the exercises I took and the tasks for each training. Each task had a report that I submitted, and the leader rejected it (here I can re-edit it and send it again) or accept it.
                                    </p>
                                    <h4>Tala Ali<span>STUDENT</span></h4>

                                </div>
                            </div>

                            <div class="carousel-item ">
                                <div class="top-top">

                                    <h2>TEAMLEADER</h2>
                                    <p>
                                        I had a wonderful experience in following up with my trainee students, giving them tasks, and informing them by sending them an email when the task was created..and notifying me when the student solved the task, and then I evaluated it for them..
                                    </p>
                                    <h4>David Spark<span>TEAMLEADER</span></h4>

                                </div>
                            </div>
                            <div class="carousel-item ">
                                <div class="top-top">

                                    <h2>SCHOOL SUPERVISOR</h2>
                                    <p>
                                        I had a successful experience with the available training system, as I was up to date with everything the student and leader were doing, knowing the training objectives and each task given to the student, and being informed of his solution to the tasks.
                                    </p>
                                    <h4>Bahaa <span>SCHOOLSUPERVISOR</span></h4>

                                </div>
                            </div>
                        </div>

                        <div class="btm-btm">

                            <ul class="list-unstyled carousel-indicators">
                                <li data-bs-target="#carousel-example-generic" data-bs-slide-to="0" class="active"></li>
                                <li data-bs-target="#carousel-example-generic" data-bs-slide-to="1"></li>
                                <li data-bs-target="#carousel-example-generic" data-bs-slide-to="2"></li>
                                <li data-bs-target="#carousel-example-generic" data-bs-slide-to="3"></li>
                            </ul>

                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</section><!-- End Testimonials Section -->
<section id="get-started" class="padd-section text-center">

    <div class="container" data-aos="fade-up">
        <div class="section-title text-center">

            <h2>Apprenticeship System </h2>
            <p class="separator">Effective Communication Between Member On System including : </p>

        </div>
    </div>

    <div class="container">
        <div class="row">

            <div class="col-md-6 col-lg-4" data-aos="zoom-in" data-aos-delay="100">
                <div class="feature-block">

                    <img src="assets/img/svg/cloud.svg" alt="img">
                    <h4> Progress Tracking</h4>
                    <p> Implemented a feature allowing students to log progress, submit assignments, and showcase their development. </p>
                    <a href="#">read more</a>

                </div>
            </div>

            <div class="col-md-6 col-lg-4" data-aos="zoom-in" data-aos-delay="200">
                <div class="feature-block">

                    <img src="assets/img/svg/planet.svg" alt="img">
                    <h4>Mentor Visibility</h4>
                    <p> Developed intuitive dashboards for both school and work mentors, revolutionizing communication methods and enhancing collaboration. </p>
                    <a href="#">read more</a>

                </div>
            </div>

            <div class="col-md-6 col-lg-4" data-aos="zoom-in" data-aos-delay="300">
                <div class="feature-block">

                    <img src="assets/img/svg/asteroid.svg" alt="img">
                    <h4>Responsive Design</h4>
                    <p> Engineered a seamlessly accessible design, ensuring the platform's responsiveness on various devices and prioritizing an optimal user experience.</p>
                    <a href="#">read more</a>

                </div>
            </div>

        </div>
    </div>

</section><!-- End Get Started Section -->
<!-- ======= Features Section ======= -->
<section id="features" class="padd-section text-center">

    <div class="container" data-aos="fade-up">
        <div class="section-title text-center">
            <h2>Amazing Features.</h2>
            <p class="separator"></p>
        </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">

            <div class="col-md-6 col-lg-3">
                <div class="feature-block">
                    <img src="assets/img/svg/paint-palette.svg" alt="img">
                    <h4>creative design</h4>
                    <p>Engineered a seamlessly accessible design, ensuring the platform's responsiveness on various devices and prioritizing an optimal user experience.</p>
                </div>
            </div>


            <div class="col-md-6 col-lg-3">
                <div class="feature-block">
                    <img src="assets/img/svg/design-tool.svg" alt="img">
                    <h4>easy to use</h4>
                    <p>Simple System to track and communication tasks between users . </p>
                </div>
            </div>



            <div class="col-md-6 col-lg-3">
                <div class="feature-block">
                    <img src="assets/img/svg/asteroid.svg" alt="img">
                    <h4>Free Updates</h4>
                    <p>For User Data and Update Information .</p>
                </div>
            </div>




            <div class="col-md-6 col-lg-3">
                <div class="feature-block">
                    <img src="assets/img/svg/code.svg" alt="img">
                    <h4>Clean Codes</h4>
                    <p>Using ASP.NET Core and the MVC architectural pattern C# .</p>
                </div>
            </div>

        </div>
    </div>
</section><!-- End Features Section -->

<section id="newsletter" class="newsletter text-center">
    <div class="overlay padd-section">
        <div class="container" data-aos="zoom-in">

            <div class="row justify-content-center">
                <div class="col-md-9 col-lg-6">
                    <form class="d-flex" method="POST" action="#">
                        <input type="email" class="form-control " placeholder="Email Adress" name="email">
                        <button type="submit" class="btn btn-default"><i class="bi bi-location-arrow"></i>Subscribe</button>
                    </form>
                </div>
            </div>

            <ul class="list-unstyled">
                <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                <li><a href="#"><i class="bi bi-instagram"></i></a></li>
                <li><a href="#"><i class="bi bi-linkedin"></i></a></li>
            </ul>

        </div>
    </div>
</section><!-- End Newsletter Section -->
<!-- ======= Contact Section ======= -->
<section id="contact" class="padd-section">

    <div class="container" data-aos="fade-up">
        <div class="section-title text-center">
            <h2>Contact</h2>
            <p class="separator">If You have any questions about our services, you can write to us HERE </p>
        </div>

        <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="100">

            <div class="col-lg-3 col-md-4" style="margin-top:50px">

                <div class="info">
                    <div>
                        <i class="bi bi-geo-alt"></i>
                        <p>Amman, Jordan</p>
                    </div>

                    <div class="email">
                        <i class="bi bi-envelope"></i>
                        <p>Apprenticeship@edu.jo</p>
                    </div>

                    <div>
                        <i class="bi bi-phone"></i>
                        <p>+962 785559760</p>
                    </div>
                </div>

            </div>

            <div class="col-lg-5 col-md-8">
                <div class="form">
                    <form asp-controller="Email" asp-action="SendEmail" method="post">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                        </div>
                        <div class="form-group mt-3">
                            <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                        </div>
                        <div class="form-group mt-3">
                            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
                        </div>
                        <div class="form-group mt-3">
                            <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                        </div>
                        <div class="text-center"><button class="btn btn-success" type="submit">Send Message</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Contact Section -->
<footer class="footer">
    <div class="container">
        <div class="row">

            <div class="col-md-12 col-lg-4">
                <div class="footer-logo">

                    <a class="navbar-brand" href="#">
                </div>Apprenticeship
                </a>

            </div>
        </div>

    </div>


</footer>

ProjectHTU/Views/Home/IndexUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Ready Bootstrap Dashboard</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link rel="stylesheet" href="/asset/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="/asset/css/ready.css">
    <link rel="stylesheet" href="/asset/css/demo.css">
</head>
<body style="margin-top:90px">
    <div class="wrapper">

        <div class="content">
            <div class="container-fluid">
                <hr />
                @if (User.IsInRole("ADMIN") || User.IsInRole("STUDENT") || User.IsInRole("SCHOOLSUPERVISOR") || User.IsInRole("TEAMLEADER"))

                {
                    <div style="margin-top:60px" class="row">
                        <div class="col-md-3">
                            <div class="card card-stats card-warning">
                                <div class="card-body ">
                                    <div class="row">
                                        <div class="col-5">
                                            <div class="icon-big text-center">
                                                <i class="la la-users"></i>
                                            </div>
                                        </div>
                                        <div class="col-7 d-flex align-items-center">
                                            <div class="numbers">
                                                <p class="card-category">Student</p>
                                                <h4 class="card-title">1,294</h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card card-stats card-success">
                                <div class="card-body ">
                                    <div class="row">
                                        <div class="col-5">
                                            <div class="icon-big text-center">
                                                <i class="la la-bar-chart"></i>
                                            </div>
                                        </div>
                                        <div class="col-7 d-flex align-items-center">
                                            <div class="numbers">
                                                <p class="card-category">TeamLeader</p>
                                                <h4 class="card-title">50</h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card card-stats card-danger">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-5">
                                            <div class="icon-big text-center">
                                                <i class="la la-newspaper-o"></i>
                                            </div>
                                        </div>
                                        <div class="col-7 d-flex align-items-center">
                                            <div class="numbers">
                                                <p class="card-category">SchoolSupervisor</p>
                                                <h4 class="card-title">20</h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card card-stats card-primary">
                                <div class="card-body ">
                                    <div class="row">
                                        <div class="col-5">
                                            <div class="icon-big text-center">
                                                <i class="la la-check-circle"></i>
                                            </div>
                                        </div>
                                        <div class="col-7 d-flex align-items-center">
                                            <div class="numbers">
                                                <p class="card-category">Admin</p>
                                                <h4 class="card-title">5</h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Task</h4>
                                    <p class="card-category">Complete</p>
                                </div>
                                <div class="card-body">
                                    <div id="task-complete" class="chart-circle mt-4 mb-3"></div>
                                </div>
                                <div class="card-footer">
                                    <div class="legend"><i class="la la-circle text-primary"></i> Completed</div>
                                </div>
                            </div>
                            <div class="card card-stats">
                                <div class="card-body">
                                    <p class="fw-bold mt-1">Statistic</p>
                                    <div class="row">
                                        <div class="col-5">
                                            <div class="icon-big text-center icon-warning">
                                                <i class="la la-pie-chart text-warning"></i>
                                            </div>
                                        </div>
                                        <div class="col-7 d-flex align-items-center">
                                            <div class="numbers">
                                                <p class="card-category">Number</p>
                                                <h4 class="card-title">150GB</h4>
                                            </div>
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="row">
                                        <div class="col-5">
                                            <div class="icon-big text-center">
                                                <i class="la la-heart-o text-primary"></i>
                                            </div>
                                        </div>
                                        <div class="col-7 d-flex align-items-center">
                                            <div class="numbers">
                                                <p class="card-category">Followers</p>
                                                <h4 class="card-title">+45K</h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-9">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">World Map</h4>
                                    <p class="card-category">
                                        Map of the distribution of users around the world
                                    </p>
                                </div>
                                <div class="card-body">
                                    <div class="mapcontainer">
                                        <div class="map">
                                            <span>Alternative content for the map</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="http://www.themekita.com">
                                APPRENTESHIP
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Help
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://themewagon.com/license/#free-item">
                                Licenses
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright ml-auto">
                    2023, made with <i class="la la-heart heart text-danger"></i> by <a href="http://www.themekita.com">HTU APPRENTISHIP</a>
                </div>
            </div>
        </footer>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="modalUpdate" tabindex="-1" role="dialog" aria-labelledby="modalUpdatePro" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <h6 class="modal-title"><i class="la la-frown-o"></i> Under Development</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <p>Currently the pro version of the <b>Ready Dashboard</b> Bootstrap is in progress development</p>
                    <p>
                        <b>We'll let you know when it's done</b>
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="/asset/js/core/jquery.3.2.1.min.js"></script>
<script src="/asset/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="/asset/js/core/popper.min.js"></script>
<script src="/asset/js/core/bootstrap.min.js"></script>
<script src="/asset/js/plugin/chartist/chartist.min.js"></script>
<script src="/asset/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
<script src="/asset/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<script src="/asset/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
<script src="/asset/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
<script src="/asset/js/plugin/chart-circle/circles.min.js"></script>
<script src="/asset/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="/asset/js/ready.min.js"></script>
<script src="/asset/js/demo.js"></script>

</html>